name: CI/CD for React, Node.js, and MySQL

on:
  push:
    branches:
      - main        
      - develop      
      - mickaelioDev 
  pull_request:
    branches:
      - main         
      - develop      
      - mickaelioDev

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js (for React)
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies (Frontend)
        run: |
          cd EventWeb/frontend
          npm install
      - name: Build React app
        run: |
          cd EventWeb/frontend
          npm run build
      - name: Deploy React app (Optional)
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Déployer l'application React sur Netlify/Vercel/Autre"

  backend:
    runs-on: ubuntu-latest
    needs: frontend 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js (for Node.js backend)
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies (Backend)
        run: |
          cd Eventweb/backend
          npm install
      - name: Run tests (Backend)
        run: |
          cd Eventweb/backend
          npm test
      - name: Migrate MySQL database (Optional)
        run: |
          echo "Migrer la base de données MySQL"
      - name: Deploy Node.js app (Optional)
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Déployer l'application Node.js sur Heroku/AWS/Autre"
